# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Etch < Formula
  desc "A terminal note-taking app inspired by Khmer wall carvings"
  homepage "https://github.com/vibolsovichea/etch"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.2/etch_0.2.2_darwin_amd64.tar.gz"
      sha256 "cf13f94cc33025d0893b7da2868b4f79adbf24a44395de6aa4a9aa362e1041ad"

      define_method(:install) do
        bin.install "etch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.2/etch_0.2.2_darwin_arm64.tar.gz"
      sha256 "d27800be5c784fc1aecabceb5fcd0154656a9dbe6fbf8e85b5dc1e51dbf3e38f"

      define_method(:install) do
        bin.install "etch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.2/etch_0.2.2_linux_amd64.tar.gz"
      sha256 "270124588e60e0c72a3168cb9b763e82ca8574414553b0d3edbd84e17211674c"
      define_method(:install) do
        bin.install "etch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.2/etch_0.2.2_linux_arm64.tar.gz"
      sha256 "1b244abe5d8806a34f4e249d6986eb6fdafea490eed90071389991170b0438b7"
      define_method(:install) do
        bin.install "etch"
      end
    end
  end

  test do
    system "#{bin}/etch", "--version"
  end
end
