# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Etch < Formula
  desc "A terminal note-taking app inspired by Khmer wall carvings"
  homepage "https://github.com/vibolsovichea/etch"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.0/etch_0.2.0_darwin_amd64.tar.gz"
      sha256 "5ef8cfc4f6a87e40782d8467683f2e956e33f15ff9849cfa56ab8ddf505a401b"

      define_method(:install) do
        bin.install "etch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.0/etch_0.2.0_darwin_arm64.tar.gz"
      sha256 "3ec9222de851331a84595b8ea7ac6df7b74c8859a109c1f5eed104cc786f29c5"

      define_method(:install) do
        bin.install "etch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.0/etch_0.2.0_linux_amd64.tar.gz"
      sha256 "6f9d9ba288abe3c965d636b00772c89d76a65b3b235a6e5bb6e027b6ade41f22"
      define_method(:install) do
        bin.install "etch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.0/etch_0.2.0_linux_arm64.tar.gz"
      sha256 "4db317f71c978febea721b3d9b8001af96c2056aabf99a8b950a1f0d67e0bb42"
      define_method(:install) do
        bin.install "etch"
      end
    end
  end

  test do
    system "#{bin}/etch", "--version"
  end
end
