# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Etch < Formula
  desc "A terminal note-taking app inspired by Khmer wall carvings"
  homepage "https://github.com/vibolsovichea/etch"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.1/etch_0.2.1_darwin_amd64.tar.gz"
      sha256 "632fd69f4645977861720638f5f34010edd592db95cd1f3d251d35c749ed69f3"

      define_method(:install) do
        bin.install "etch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.1/etch_0.2.1_darwin_arm64.tar.gz"
      sha256 "47a94ef4af3ca412a7642aad4e865b859ef970ad3099f0904bcd318112d0f1bc"

      define_method(:install) do
        bin.install "etch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.1/etch_0.2.1_linux_amd64.tar.gz"
      sha256 "a80ea8fa1b1be39ea1e468ae606040afdb802befa618ee81dffbbcb9a0203215"
      define_method(:install) do
        bin.install "etch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/etch/releases/download/v0.2.1/etch_0.2.1_linux_arm64.tar.gz"
      sha256 "488560fcd1b13ef15dad17af6d11dcda614eec319c8b91fa80c665e5ed474f64"
      define_method(:install) do
        bin.install "etch"
      end
    end
  end

  test do
    system "#{bin}/etch", "--version"
  end
end
