# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scripture < Formula
  desc "Deprecated. Use etch instead."
  homepage "https://github.com/vibolsovichea/etch"

  depends_on "etch"

  def install
    bin.install_symlink "etch" => "scripture"
  end

  def caveats
    <<~EOS
      scripture has been renamed to etch.
      Please run:
        brew uninstall scripture
        brew install etch
    EOS
  end
end