# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scripture < Formula
  desc "A terminal note-taking app inspired by Khmer wall carvings"
  homepage "https://github.com/vibolsovichea/scripture"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vibolsovichea/scripture/releases/download/v0.1.2/scripture_0.1.2_darwin_amd64.tar.gz"
      sha256 "b2c8effdcb055fca431a90b8040197443e108d42be98ccbcc58b51b87c1a5c1d"

      define_method(:install) do
        bin.install "scripture"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vibolsovichea/scripture/releases/download/v0.1.2/scripture_0.1.2_darwin_arm64.tar.gz"
      sha256 "5186ee4599f7946840e869fac02bf8edc375a48c2aaf8ab1ca7fccf6ed65d3d8"

      define_method(:install) do
        bin.install "scripture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/scripture/releases/download/v0.1.2/scripture_0.1.2_linux_amd64.tar.gz"
      sha256 "6841020a6c7634d229a1efa82a17b49754419bd369043f9c18bc3d256d5cc74b"
      define_method(:install) do
        bin.install "scripture"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vibolsovichea/scripture/releases/download/v0.1.2/scripture_0.1.2_linux_arm64.tar.gz"
      sha256 "8d1bf4b6b955aae841b97ff35f28b6e4763e03008d855c57c108711e6409d4f4"
      define_method(:install) do
        bin.install "scripture"
      end
    end
  end

  test do
    system "#{bin}/scripture", "--version"
  end
end
